"""Add care_instructions and watering_frequency to Plant

Revision ID: c8bad824e9aa
Revises: 28002713e436
Create Date: 2025-02-13 00:18:39.841655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8bad824e9aa'
down_revision: Union[str, None] = '28002713e436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('care_instructions', sa.String(), nullable=True))
    op.add_column('plants', sa.Column('watering_frequency', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'watering_frequency')
    op.drop_column('plants', 'care_instructions')
    # ### end Alembic commands ###
